BASE_VERSION=19
COMPANY_NAME=bjit
DOMAIN=app-odoo.bjitgroup.org

DB_USER=bjit
DB_PASS=Bjit@#2024

PGADMIN_EMAIL=bjit@bjitgroup.org
PGADMIN_PASS=Bjit@#2024

ODOO_ADMIN_PASS=Bjit@#2024

ENTERPRISE_PATH_16=/opt/odoo/server/odoo_16.0+e/odoo/addons
ENTERPRISE_PATH_17=/opt/odoo/server/odoo_17.0+e/odoo/addons
ENTERPRISE_PATH_18=/opt/odoo/server/odoo_18.0+e/odoo/addons
ENTERPRISE_PATH_19=/opt/odoo/server/odoo_19.0+e/odoo/addons