ARG ODOO_VERSION=19
FROM odoo:${ODOO_VERSION}

USER root

# Faster mirror
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://us.archive.ubuntu.com/ubuntu|' /etc/apt/sources.list

# Install system tools
RUN apt-get update && apt-get install -y \
    python3-pip \
    nano \
    && rm -rf /var/lib/apt/lists/*
USER odoo