[options]
admin_passwd = Bjit@#2024
db_user = bjit
db_password = Bjit@#2024
db_host = db
db_port = 5432
addons_path = /mnt/extra-addons
db_filter = ^test19ce_odoo19_db$
proxy_mode = True
logfile = /var/log/odoo/test19ce_odoo19.log
without_demo = False
