[options]
admin_passwd = Bjit@#2024
db_user = bjit
db_password = Bjit@#2024
db_host = db
db_port = 5432
addons_path = /mnt/odoo-19-ee,/mnt/extra-addons
db_filter = ^bjit_odoo19_db$
proxy_mode = True
logfile = /var/log/odoo/bjit_odoo19.log
