[options]
admin_passwd = Bjit@#2024
db_user = bjit
db_password = Bjit@#2024
db_host = db
db_port = 5432
addons_path = /mnt/extra-addons
db_filter = ^test18ce_odoo18_db$
proxy_mode = True
logfile = /var/log/odoo/test18ce_odoo18.log
without_demo = False
