[options]
admin_passwd = Bjit@#2024
db_user = bjit
db_password = Bjit@#2024
db_host = db
db_port = 5432
addons_path = /mnt/extra-addons
db_filter = ^test17ce_odoo17_db$
proxy_mode = True
logfile = /var/log/odoo/test17ce_odoo17.log
without_demo = False
