[options]
admin_passwd = Bjit@#2024
db_user = bjit
db_password = Bjit@#2024
db_host = db
db_port = 5432
addons_path = /mnt/odoo-18-ee,/mnt/extra-addons
db_filter = ^demo_odoo18_db$
proxy_mode = True
logfile = /var/log/odoo/demo_odoo18.log
without_demo = False
